name: Java GitHub CI/CD Actions with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
#  contents: { read , write}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Run tests
#        run: ./gradlew test
#
#      - name: Publish test results
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-results
#          path: build/test-results
#
#      - name: Archive JAR file
#        uses: actions/upload-artifact@v2
#        with:
#          name: application
#          path: build/libs/*.jar
