name: Java CI/CD with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results

      - name: Archive JAR file
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: build/libs/*.jar
